### ISSUE TITLE
Water one

### ISSUE THREAD

**Issue by Tanyuu** [Real-king-Ph/2020NEFU-ACMERs#2]

**Comment by Real-king-Ph** [comment]
哈哈(ಡωಡ)hiahiahia发自我的华为手机-------- 原始邮件 --------发件人： Tanyuu <notifications@github.com>日期： 2020年12月9日周三 晚上10:06收件人： Real-king-Ph/2020NEFU-ACMERs <2020NEFU-ACMERs@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [Real-king-Ph/2020NEFU-ACMERs] Water one (#2)

Let me water one firstly.

For the first reason, I want to expreience how to submit the issure.A  Engilsh-only system is sooo unfriendly for me, who is with his poor English.

So that, for the second reason, 我想试一试中文行不行。

HiaHiaHia.

My water is over.
